### ISSUE TITLE
support mir.fft : thin wrapper around fftw for ND convolution

### ISSUE THREAD

**Issue by timotheecour** [9il/dip80-ndslice#332] opened 2016-09-13 08:10 UTC
The goal should be to be as efficient as possible (eg by providing a user friendly wrapper around fftw; note that https://dlang.org/library/std/numeric/fft.html is slow compared to fftw IIRC)

**Comment by 9il** [comment] 2016-09-13 08:23
Duplicate of #45. Mir will have its own fft with the same spead as fftw (GLAS is fast as OpenBLAS, so I think we can do our fftw analog in D).

**Closed as completed by 9il** 2016-09-13 08:23 UTC
Labels: duplicate

**Comment by p0nce** [comment] 2016-11-27 14:02
Note that the dplug:dsp package has a FFT that works with real inputs (public domain + boost license).
Might be used for 1d convolution only.

**Comment by timotheecour** [comment] 2016-11-27 22:54
to reproduce:

main.d:
import ggplotd.gtk;
void main(){
}


dub.json:
{
 "targetType": "executable",
 "sourcePaths":["."],

 "dependencies": {
 "ggplotd": ">=1.1.0",
 },

 "subConfigurations": {
  "ggplotd": "ggplotd-gtk",
 },
 "buildRequirements": ["allowWarnings"],
}

**Comment by timotheecour** [comment] 2016-11-27 23:00
@ p0nce:
well there is already https://dlang.org/phobos/std_numeric.html#.fft but it's much slower than fftw.

@9il:
fftw is quite a large library, matching the speed would probably take a lot of effort/time; in the meantime having user friendly wrappers would be nice to have

**Comment by 9il** [comment] 2016-11-28 01:55
> fftw is quite a large library, matching the speed would probably take a lot of effort/time; in the meantime having user friendly wrappers would be nice to have

Agreed (but time constraints)
