### ISSUE TITLE
auto a=[[1,2],[3,4]].ndarray; // how to do that? (doens't compile)

### ISSUE THREAD

**Issue by timotheecour** [9il/dip80-ndslice#380] opened 2016-12-03 04:14 UTC
eg: (but of course needs to be more general in terms of a.shape.length)

```
auto makeSlice2(T)(T a){
  alias T2=typeof(a[0][0]);
  auto b=slice!T2(a.length, a[0].length);
  b[]=a;
  return b;
}

unittest{
  auto vals=[[1,2],[3,4],[3,6]];
  auto a=makeSlice2(vals);
  assert(a==vals);
  assert(a.shape==[3,2]);
}
```

NOTE:
```
auto makeSlice2(T)(T a){
  return a.sliced.unpack;
}
```
doesn't do what i would expect

**Comment by 9il** [comment] 2016-12-03 08:49
`ndarray` converts slice to a common d array.

You may want to use following steps:
```d
auto sh = a.shape; // computes shape, can throw `SliceException`
auto b = uninitializedSlice(sh);
b[] = a;
```

I will deprecate `shape` and `reshape` functions, so they will be `nothrow` and `@nogc` but an addition `err` reference parameter will be added.

**Comment by 9il** [comment] 2016-12-03 08:53
Duplicate of https://github.com/libmir/mir/issues/336

**Closed as completed** 2016-12-03 08:53 UTC
Labels: duplicate, question

**Comment by 9il** [comment] 2018-02-18 10:07
See also http://docs.algorithm.dlang.io/latest/mir_ndslice_fuse.html#.fuse
