### ISSUE TITLE
slice doesn't accept an init value

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#202] opened 2016-04-29 10:10 UTC
It is possible to do:

```
auto tup = makeSlice!int(Mallocator.instance, [2, 3, 4], 10);
```

but not

```
auto sl = slice!int([2, 3, 4], 10);
```

**Comment by 9il** [comment] 2016-04-29 10:28
This is by design. When you create an array, you have not ability to set фт initial value. But when you make array you have this ability

**Comment by wilzbach** [comment] 2016-04-29 10:43
> This is by design. When you create an array, you have not ability to set initial value. But when you make array you have this ability

Imho we should still provide this API to the user as he gets confused otherwise.
I discovered this when I tried to write up a [changelog](https://github.com/dlang/phobos/pull/4260) for mir, so I used myself as guinea pig.

**Comment by 9il** [comment] 2016-05-02 07:46
Fixed with https://github.com/dlang/phobos/pull/4260

**Closed as completed by 9il** 2016-05-02 07:46 UTC
Labels: move to Phobos
